language: node_js
node_js:
- '8'
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - secure: fDH2TYmtrZk0aWGZAQsf+SwZ2JGQEvf3zyBrMimOSBkD8/F8YChOQd7H1o2W2gpw8+KzNJIleR3AI57Hj8mFrGET6hebKAkz4bn9oMg+AWEAv33pjmhCANqY19Htpx2BKVqS7iogn3DDEV4I1Ab/lUvqEG0oXsNf93PnktGdBteuCSG2tLzC3IOsSFtr0Q204glhPXVv3yvZJ5h9tov7YHfYYoz/pghu/V9HzOhHCfT02ZKQvTZbmT7ryRxxhh8FTznCpq/oDBqGKiKnmIKtBaZC7SIObhiRnZyLvzPuk0EcYBZxzhzxfRZqqcLgF1hoozTxdBpyrzONMjmGC3RHePjOMov6UTmdYlHa2m1hSu/VbvtqaS9zaXMyplTat9YlrpK8JRGUr/tN5q+kDZGOppLssKzhxCH9YtK7kFu/PzFlJ9sqRb4MrwQ/OLZ40/uYj1tgeiOub3VWOBsE1AwXvoDqifXsqziDV+kFNb3eI0MejiQG1hyeDelhZQlGCDSRz6tYvlarjNrfFUg11K/xkRT2xO1oVHw+qoKW9yygR/6yRKyzEu+aE/J0ES919yH3dhx2UlVtjP7xbu5PCRtDiZCaDMaFdSg9XvyUQ3oVfe/wkdhB4cNdemQBMZ9+TTv1slx3gJXm5I1zGxyjDi92MBOquCLIPBjxIFwf6zv6ae4=
  - secure: f95zQQ2wsho4EIgVYAR4PweQaPpXqqPK0dfpsJhvbUnRHRTqgl5dLKDtiKvewNhluEGTZ/M1tw5078SutUf7Rg9rH0mqhh+pn294U391jatWntSUKM8xzGpfnM4RXKZCAWfIbin1/AjlQR8uGGi5tgU1I1tC5GILjoewudU/x7Q/OWIGzUtd5doW8a6YGOVUZled/EKqe34gWxUp6+jXNMM2I/XSfrmzOzd0bfb80RXvXX+yhKJHfjmfLU0F5nBKGDhNzHzCarqJ1mVFu6fwxvVFgMjhy1GfEr3JmONPkPm6roI5XYe/0vhZk4H6aE9N6MXNYLqVvx7Zsm+0LrStsyO/tuMW7viseUknPyOR23IXuoom91uGLFZid0hG4Mn4dft0RN0YOTLB50wuoq5rxel6IFghw+DMR2E8ldDFdIfdIBK0EHH+coqMSOSCedGPDRg3/CHJAYMWgEFiUjEGHJ0npnQEGwQQZ+b1kvYZGeB8hQ86hXFAu2jq87sZYrr7y/4hDTBS9y52r+xGkrem/2HqF6OO+JfWtibiOAkCMTq5KlTlM4ZmZalcM6yjPdhSQvm4pmrGyUntViD7cuRfTo+qs6OB7/2lSFuLqcYhc54tvGw7IQCyHlvrX3Jz4gjjSX4yMofl5RaQBnAwr0Wr7ENQ+XavjfCuE5InoOaYMrg=
before_script: npm run build
before_deploy: pip install --user awscli
deploy:
- provider: script
  script: npm run deploy:staging
  skip_cleanup: true
  on:
    branch: master
