# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# build cache to preserve files/folders between builds
cache:
  - node_modules                    # local npm modules
  - '%APPDATA%\npm-cache'           # npm cache

# scripts that run after cloning repository
install:
  # Install node 4.2.1
  - ps: Install-Product node 4.2.1
  # Install npm 3.3.6
  - npm install -g npm@3.3.6
  # install modules
  - npm install

# to run your custom scripts instead of automatic tests
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't build with msbuild.
build: off
